### ISSUE TITLE
تنظيم حقول استمارة الإدراج

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#11]
مطلوب إعادة تنظيم حقول استمارة إدراج مُدخلة الدواء بحيث:
-  تكون بيانات الدواء في قسم و بيانات الاتّصال في قسم
-تتابع حقول بيانات الدواء كالتالي:
1. الاسم بالعربية و اللاتينية
1. تاريخ انتهاء الصلاحية
1. حالة العبوة
1. المحافظة
1. ملاحظات
- تتابع حقول بيانات الاتّصال كالتالي:
1. الاسم
1. عنوان البريد الإلكتروني
1. خيار عدم إظهار عنوان البريد الإلكتروني
1. رقم الهاتف
1. الموافقة على شروط الاستخدام

**Comment by 3XMSG** [comment]
تم التعديل
