### ISSUE TITLE
تحكّمات اختيار التاريخ

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#13]
تطبيق تحّكمات اختيار التاريخ كقائمة منسدلة غير منسب.
كما أن فرضية تحديد عدد من السنوات المستقبلية نصّا غير عملي و قد يكون معيقا للاستخدام إذا ما وُجدت أدوية مدة صلاحياتها أبعد مما نفترضه في القائمة النصّية الثابتة.

مطلوب تطبيق تحكم اختيار التاريخ كرزنامة

**Comment by gundour** [comment]
datepicker.js is a jquery plugin that I used for selecting dates
