### ISSUE TITLE
رقم الهاتف ليس مطلوبا في حال قبول إظهار عنوان البريد الإلكتروني

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#15]
حاليا، عند إدخال عنوان بريد إلكتروني مع عدم تأشير خيار عدم إظهار عنوان البريد الإلكتروني فإن الاستمارة لا يمكن إيداعها إلا بإدخال رقم هاتف

**Comment by 3XMSG** [comment]
تم التصحيح
