### ISSUE TITLE
لغة رسائل الخطأ لقيم الحقول المدخلة في استمارة الإيداع

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#16]
حاليا تظهر رسائل الخطأ لقيم الحقول المدخلة غير المقبولة بالإتكليزية. المطلوب ظهورها بالعربية.

**Comment by agharbeia** [comment]
ممكن تقول لي موضع ورود النصوص في الكود و أنا أترجمها يا @3XMSG

**Comment by 3XMSG** [comment]
ممكن نعمل رسالة موحدة عند عدم ادخال قيمة فى الحقول الإجبارية لتنبيه المستخدم للإدخال ، و فى حقول الإيميل الرسالة تعرض الشكل المتوقع  للإيميل

**Comment by 3XMSG** [comment]
تم التصحيح
