### ISSUE TITLE
تقريب النتائج عند عدم الإيجاد

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#23]
عند عدم وجود نتائج للبحث، يمكن اقتراح أسماء قريبة مما بحث عنه الطالب مما هو موجود بالفعل في الإدراجات.
الاقتراحات لا تظهر نتائج تلقائيا، بل تقترح أسماء تقريبية هي روابط إلى عمليات بحث حديدة، يختار منها المستخدم الاسم المطلوب.
الغرض منها تدارك أخطاء البحث.

**Comment by gundour** [comment]
يقوم النظام بإقتراح مجموعة من النتائج القريبه بناءً على البيانات الموجوده فى قاعدة البيانات
