### ISSUE TITLE
المحافظة city!!

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#28]
حسب ما هو في [النسخة الحالية من /data/methods.js](https://github.com/arabdigitalexpression/dawasawa/blob/212f7e8a149289327c2609dfaa869f3a3e543f52/app/data/methods.js)

المحافظة مرموز لها بالمتغيّر city

أنا عارف أن الكود شغّال و مايفرقش، لكن جودة الكود تفرق في المستقبل، و علشان نقدر نقراه و نفهمه، بالذات أننا مش كاتبين توثيق حقيقي للكود.
كمان لاحقا يمكن نزوّد المدن، و ساعتها هتكون عندنا هياكل بيانات و كود يلخبطنا أو يعمل مشاكل.

**Comment by 3XMSG** [comment]
بعض المتغيرات فى الملفات القديمة ممكن يكون لها تسمية مختلفة عن الملفات التى تم تحديث إسم المتغيرات فيها و ده فعلاً محتاج مراجعة على الأسماء
