### ISSUE TITLE
تلبيدة الأمارة غير آمنة

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#30]
حسب ما هو في [النسخة الحالية من /data/methods.js](https://github.com/arabdigitalexpression/dawasawa/blob/212f7e8a149289327c2609dfaa869f3a3e543f52/app/data/methods.js)
فحاليا توليد الامارة يعتمد على قيمة عنوان البريد الإلكتروني للمستخدم وحدها!
دا معناه أن مالهاش أي لازمة لأنه تمكن إعادة توليدها بمعرفة الخوارزمية المستخدمة (الكود علني) و عنوان البريد
أي تلبيدة لتكون آمنة يجب تصمين عنصر سري في مدخلاتها، يسمى عادة "الملح" salt.
[طالع صفحات التصميم في ويكي أضف للمزيد](https://arabdigitalexpression.org/wiki/%D8%AA%D8%B5%D9%85%D9%8A%D9%85:%D8%AF%D9%88%D8%A7%D8%B3%D9%88%D8%A7/cryptographic-token)

الملح يجب أن يكون حزمة طويلة مولّدة عشوائيا و يستحسن أن تُحفظ في ملف config 
و ساعتها يجب عدم ترك القيمة المستعملة في ملفات الكود العلنية، فيكون مطلوب تعميتها باستخدام git-crypt زي ما تكلمنا من قبل.

كذلك استعمال الأمارة يتطلب تمرير بياناتها غير السرية معها. الأمارة وسيلة للتأكد من أن الطالب معه تصريح، لكن لا توجد وسيلة لاستخراج بيانات الطلب من الأمارة نفسها، فإما نحفظ بيانات الطلب في مخزن بياناتنا مؤقتا إلى حين البت في الطلب (يبدةو أنّك عامل كدا)، أو لتقليل البيانات الملوب منّا حفظها و هو الاتجاه ال أفضّله فيمن تمرير بيانات الطلب مرة أخرى مع الأمارة لإعادة حساب الأمارة عند استلام الطلب.

لو بيانات الطلب طويلة و أو معقدّة فالحل البديل لاستخدام تلبيدة هو أن تحوي الأمارة ه الطلب بكل بياناته معمّاة بمفتاح سرّي، AES مثلا، و دا فائدته أننا نقدر نستخرج بيانات من الأمارة فنقدر نخزن فيها معلومات أكثر لطلبات أعقد.

**Comment by agharbeia** [comment]
@3XMSG تعال نتكلّم في استعمال التعمية بدل التلبيدة لتوليد الأمارة. لو حاسس أنّك تقدر تنجزها في يوم يكون أحسن نعمل كدا.
الميزة هتكون أنك ماتحتاجش تحفظ بيانات الطلب زي ما أنا شايف في الكود من tokenSchema
في كلّ الأحوال التطبيق الحالي للأمارات مش نافع لأنه غير آمن، و محتاج شغل قبل الإطلاق و التجريب حتّى: #29 و #30 و #32 و #33

شًف: https://www.npmjs.com/package/crypto-js#object-encryption

**Comment by agharbeia** [comment]
In this case we have a data structure `user_request`, where:
`
var userRequest = {
userID: email_address
action: [instate | retrieve_listing | delete ]
objectID:
timestamp:
}
`

This structure is then encrypted and sent to the user as an item on a URL link that the user should follow to confirm the verb. So:

`var ciphertext = CryptoJS.AES.encrypt(JSON.stringify(userRequest), 'secret key 123');`

then encoded:

`token = Base62.encode(ciphertext)`

The token is used to create a URL sent to the user in the confirmation-request message:
`https://dawasawa.online/enstate/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`

or shown on the website:
`https://dawasawa.online/delete/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`

When returned, the request is decrypted and verified, then executed.

**Comment by 3XMSG** [comment]
@agharbeia شوف الحل الأخير ، قمت بإستخدام bcrypt .لتعمية الامارات
