### ISSUE TITLE
 الأمارة لا تتضمن الفعل

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#31]
حسب ما هو في [النسخة الحالية من /data/methods.js](https://github.com/arabdigitalexpression/dawasawa/blob/212f7e8a149289327c2609dfaa869f3a3e543f52/app/data/methods.js)
فالأمارة المولد لأفعال توكيد الإدراج و استرجاع قائمة الإدراجات لا تتضمن الفعل المطلوب، و الصادرة بشأنه الأمارة
دا معناه أنه يمكن استعمال التلبيدة لأي فعل بمجرّد الحصول على الأمارة.
أحيانا دا مش هيكون له أثر، زي في حالة استخدام أمارة عرض الإدراجات ثم تمريرها إلى طلب توكيد إدراج، لكنه هيسبب عطل في النظام.
لكن معناه كمان أن أي أفعال تتطلب استيثاق حقيقي في المستقبل ممكن التحايل عليها.
طالع https://arabdigitalexpression.org/wiki/تصميم:دواسوا/cryptographic-token

**Comment by 3XMSG** [comment]
الأمارة لا تولد عن طريق الإيميل فقط و لكن وقت الطلب أيضا أحد العوامل التى يتم بها التوليد و هو لن يتكرر ابداً، كما أن قيم الأمارات المولده تُسجل فى قاعدة البيانات لمدة محددة ثم يتم حذفها نهائياً
