### ISSUE TITLE
حساب صلاحية الأمارة

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#49]
في [/routes/mylist.js:function authenticate](https://github.com/arabdigitalexpression/dawasawa/blob/f13a24ed47b53044ecdeb4dd1483c67753f16b9b/app/routes/verify.js) و [/routes/mylist.js:function](https://github.com/arabdigitalexpression/dawasawa/blob/f13a24ed47b53044ecdeb4dd1483c67753f16b9b/app/routes/mylist.js) authenticateEmail
المنطق في دالة التحقق من صلاحية الأمارة غير صحيح.
كذلك أقترح عمل دالة واحدة مجرّدة، في methods مثلا و استعمالها حيثما يلزم، لتقليل تكرار الكود و تقليل احتمالات الخطأ و بالتالي أعباء الصيانة.

**Comment by gundour** [comment]
تم التعدبل فى النسخه الأخيرة
