### ISSUE TITLE
استبدال خط النصوص الطويلة

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#50]
الخط المستخدم حاليا للنصوص في الموقع صعب لقراءة.
هو خط ملائم للعناوين لكن ليس للنصوص الطويلة>
أقترح استعمال خط حرّ مناسب آخر مثل شهرزاد أو الأميري لصفحات النصوص الطويلة، و الإبقاء على كايرو لعناصر واجهة المستخدم و العناوين.

**Comment by gundour** [comment]
fixed in the latest version

**Comment by agharbeia** [comment]
أنا مش شايف فرق في الخط يا @3XMSG 
هو الخط المستعمل حاليا اسمه إيه؟

**Comment by gundour** [comment]
Lateef

**Comment by agharbeia** [comment]
شكرا. لاحظت الفرق أما بصيت كويس.
