### ISSUE TITLE
Error message for bad token in confirmation of submission

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#60]
When a corrupt confirmation token is used, an un-handled exception results in a call stack.
Instead, there must be an intelligible message.

**Comment by agharbeia** [comment]
This must apply to all error messages pertaining to tokens.
See also #59.

**Comment by gundour** [comment]
this error is handled in the latest version

**Comment by agharbeia** [comment]
أنا مش شايف تغيير يا @3XMSG ؟
إيه هو الخط المستخدم حاليا؟
