### ISSUE TITLE
Ephemeral error and success messages

### ISSUE THREAD

**Issue by agharbeia** [arabdigitalexpression/dawasawa#68]
Messages pertaining to errors with connectivity with the back-end server and/or failures to submit forms cannot be ephemeral.

It's very common for users to submit a form and switch to another task - on the computer or else - with the intention of returning later to check on the results of their actions.
Missing out on a failure messages will leave users puzzled; not knowing whether their request were successful.

The same for success messages for listing entries where repeating the successful action could lead to duplicate messages received; thus to user confusion on what the site has for/about them now!

**Comment by gundour** [comment]
fixed in the last push

the error messages are now modals that will stay on the screen until the user close it
